<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundfacebook'); ?>
<?php
$form = $this->form;
$form->prepare();

// TODO : refactor message display
$fm = $this->flashMessenger()->setNamespace('playgroundfacebook')->getMessages();
if (isset($fm[0]))
{
    echo '<span class="alert">' . $fm[0] . '</span>';
}
?>

<h1>Choisir une page pour l'appli FB</h1>


<?php echo $this->form()->openTag($form) ?>

<div class="facebook-admin">
    <?php //echo $this->formHidden($form->get('id')); ?>

    <div class="label-input">
        <?php echo $this->formLabel($form->get('idApp')); ?>
        <?php echo $this->formHidden($form->get('idApp')); ?>
        <span><?php echo $this->appName; ?></span>
    </div>

    <div class="label-input">
        <?php echo $this->formLabel($form->get('idPage')); ?>
        <?php echo $this->formSelect($form->get('idPage')); ?>
        <?php echo $this->formElementErrors($form->get('idPage')) ?>
    </div>

</div>

<?php $form->get('submit')->setLabel($this->translate('Choisir')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<?php echo $this->form()->closeTag() ?>
